
###############################################################################
#
# Inclusive Makefile for the x86_64_mlnx_msn4800 module.
#
# Autogenerated 2021-05-03 20:19:20.866896
#
###############################################################################
x86_64_mlnx_msn4800_BASEDIR := $(dir $(abspath $(lastword $(MAKEFILE_LIST))))
include $(x86_64_mlnx_msn4800_BASEDIR)module/make.mk
include $(x86_64_mlnx_msn4800_BASEDIR)module/auto/make.mk
include $(x86_64_mlnx_msn4800_BASEDIR)module/src/make.mk

